### ISSUE TITLE
Capturing images at full resolution

### ISSUE THREAD

**Issue by blakesanie** [expo/expo-camera#3]
Is there any way to take a picture at full resolution? The docs for expo camera say to use this.camera.getAvailablePictureSizesAsync, but when I run the code on my device, the function cannot be found. Also, in the readme for this repo, the prop "pictureSize" has disappeared... how can we accomplish taking photos at full res?

**Comment by sjchmiela** [comment]
Hey @blakesanie! Documentation available at [docs.expo.io](https://docs.expo.io/versions/latest/sdk/camera) is also valid for `expo-camera` distributed. as a standalone package, so `pictureSize` prop should work all right.

It'd be strange if there was a Camera instance reference and still it wouldn't have `getAvailablePictureSizesAsync` method… Is the issue reproducible on Snack, or do you use this library as a universal module without ExpoKit?

**Comment by sjchmiela** [comment]
Hey, I hope my comment has cleared the misunderstanding. This repo is being deprecated in favor of `expo/expo`, so all the changes and documentation will be available at `expo/expo`. 🙂
