### ISSUE TITLE
Old version of cameraview

### ISSUE THREAD

**Issue by pserrer** [expo/expo-camera#4]
I tried to add the expo-camera to a react native project and failed building it, because of wrong dependencies to com.google.android:cameraview.

Event if I manually add `maven { url "$rootDir/../node_modules/expo-camera/android/maven" }` or `maven { url "https://github.com/expo/expo-camera/raw/master/android/maven" }` the build still fails, because the included version 1.0.0 of cameraview is to old for this project (missing method `getCameraId` in `ExpoCameraView`)

**Comment by sjchmiela** [comment]
Hey @pserrer, could you please try using `expo-camera@1.1.1-rc.0` published today? It’s cameraview has been updated, sorry for the inconvenience. 😔
