### ISSUE TITLE
Large video size

### ISSUE THREAD

**Issue by charlesoma** [expo/expo-camera#5]
I have an app I built with expo. It uses expo-camera to record videos. The problem is that the videos are too large so I'm wondering if there's a way to compress a recordAsync video.

**Comment by bbarthec** [comment]
Hey @charlesoma. Try to experiment with `recordAsync` by passing `options` param with `quality` set to some lower value (by default max possible value is set).

**Comment by charlesoma** [comment]
Hello @bbarthec, I have done as you suggested and that actually helped reduce the video file size a bit. But I need it further reduced and optimized, is there another way to get this done?

**Comment by sjchmiela** [comment]
Hey, this would require some advanced post-processing, which we do not support at the moment, unfortunately. 😞 Maybe you could upvote an existing feature request or create a new one on https://expo.canny.io? 🙂
