### ISSUE TITLE
Picture Frame Guides

### ISSUE THREAD

**Issue by m-a-r-c-e-l-i-n-o** [expo/expo-camera#6]
Hello there!

Any plans to add support for frame guides to help the user better focus on barcodes and/or other regions of a picture? 

Maybe something along the lines of:
```
<Camera
    frame={true} // enable and disable frame guides
    frameColor={"green"} // The color of the borders of the frame guides
    frameRatio = {16:9} // The ratio of the frame
/>
```
I suppose it could always be centered and stretched to the max width or height allowed by the ratio, with maybe a 10% padding for clarity.

Thanks for the expo system, really loving it!

**Comment by sjchmiela** [comment]
Hey, @m-a-r-c-e-l-i-n-o!

I'm not sure what you mean by frame guides, but if what you mean are these guiding lines in the live preview of the camera, like:

![camera app screenshot](https://user-images.githubusercontent.com/1151041/46726707-319bb100-cc7f-11e8-8d80-e629344c93c8.png)

then you can do it on your own! `Camera` component accepts children, so you could design such frames component yourself and pass in as a child. 🙂

**Comment by sjchmiela** [comment]
I'll close this issue as the frame guides can be implemented by the developer (putting it into `expo-camera` wouldn't necessary align with the purpose of this package). 🙂
